[package]
name = "rum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3"
tokio-postgres = {version = "0.7", features = ["with-time-0_3"]}
bytes = "*"
tokio = { version = "1", features = ["full"] }
thiserror = "*"
parking_lot = "*"
once_cell = "*"
tracing = "*"
tracing-subscriber = "*"
pluralizer = "0.4.0"
rum-macros = { path = "../rum-macros" }
colored = "2"
